# Generated by Django 4.2.1 on 2024-08-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('file_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
